name: Build deps

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          repository: libsdl-org/SDL

      - run: |
          sudo apt install -y ninja-build libxi-dev

          mkdir build
          cd build

          cmake -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang -DCMAKE_BUILD_TYPE=Release \
            -DSDL_ATOMIC_ENABLED_BY_DEFAULT=OFF \
            -DSDL_AUDIO_ENABLED_BY_DEFAULT=OFF \
            -DSDL_RENDER_ENABLED_BY_DEFAULT=OFF \
            -DSDL_HAPTIC_ENABLED_BY_DEFAULT=OFF \
            -DSDL_POWER_ENABLED_BY_DEFAULT=OFF \
            -DSDL_THREADS_ENABLED_BY_DEFAULT=OFF \
            -DSDL_TIMERS_ENABLED_BY_DEFAULT=OFF \
            -DSDL_FILE_ENABLED_BY_DEFAULT=OFF \
            -DSDL_LOADSO_ENABLED_BY_DEFAULT=OFF \
            -DSDL_CPUINFO_ENABLED_BY_DEFAULT=OFF \
            -DSDL_FILESYSTEM_ENABLED_BY_DEFAULT=OFF \
            -DSDL_DLOPEN_ENABLED_BY_DEFAULT=OFF \
            -DSDL_SENSOR_ENABLED_BY_DEFAULT=OFF \
            -DSDL_LOCALE_ENABLED_BY_DEFAULT=OFF \
            \
            -DBUILD_SHARED_LIBS=OFF -DSDL_STATIC_PIC=ON -D3DNOW=OFF -DVIDEO_VULKAN=OFF \
            ..

          ninja

      - uses: actions/upload-artifact@v2
        with:
          path:
            build/libSDL2.a

  commit:
    runs-on: ubuntu-20.04
    needs: [ build-linux ]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: actions/download-artifact@v2

      - run: |
          mv artifact/libSDL2.a utils/deps/libsdl_x64.a

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -u
          git commit -m generated
          git push
