name: Build angle

on:
  push:
    paths:
      - .github/workflows/build-angle.yml
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            ext: so
          - os: windows-latest
            ext: dll

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - run: |
          git clone --depth=1 https://chromium.googlesource.com/angle/angle.git
          git clone --depth=1 https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - if: ${{ matrix.os == 'ubuntu-20.04' }}
        env:
          SETUP_ENV: export PATH="$PWD/depot_tools:$PATH"

      - if: ${{ matrix.os == 'windows-latest' }}
        env:
          SETUP_ENV: $env:DEPOT_TOOLS_WIN_TOOLCHAIN=0; $env:PATH += ";$pwd\depot_tools"

      - working-directory: angle
        run: |
          ${{ env.SETUP_ENV }}

          python scripts/bootstrap.py
          gclient sync
          git checkout master
          git apply -p1 ../utils/angle_fixes.patch

      - if: ${{ matrix.os == 'ubuntu-20.04' }}
        run:
          ./angle/build/install-build-deps.sh

      - working-directory: angle
        run: |
          ${{ env.SETUP_ENV }}

          gn gen out/Release --args="is_clang=true is_component_build=false angle_enable_null=false is_debug=false is_official_build=true chrome_pgo_phase=0 use_thin_lto=true init_stack_vars=false"
          cd out/Release
          ninja libEGL

          cd ../..
          gn gen out/Debug --args="is_clang=true is_component_build=false angle_enable_null=false"
          cd out/Debug
          ninja libEGL

      - uses: actions/upload-artifact@v2
        with:
          path: |
            angle/out/Debug/libEGL.${{ matrix.ext }}
            angle/out/Debug/libGLESv2.${{ matrix.ext }}
            angle/out/Release/libEGL.${{ matrix.ext }}
            angle/out/Release/libGLESv2.${{ matrix.ext }}

  commit:
    runs-on: ubuntu-20.04
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: actions/download-artifact@v2

      - run: |
          mkdir -p bin/angle
          mkdir -p bin/angle_debug

          mv artifact/Release/* bin/angle
          mv artifact/Debug/* bin/angle_debug

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add
          git commit -m generated
          git push
