name: Build deps

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  BUILD_CMD: -fno-stack-protector -O3 -msse3 -DNDEBUG main.c

jobs:
  build-linux:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          repository: libsdl-org/SDL

      - run: |
          sudo apt install -y libasound2-dev libxi-dev
          mkdir build
          cd build

          cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang -DCMAKE_BUILD_TYPE=Release -D3DNOW=OFF -DBUILD_SHARED_LIBS=OFF -DSDL_STATIC_PIC=ON \
            -DSDL_ATOMIC_ENABLED_BY_DEFAULT=OFF \
            -DSDL_RENDER_ENABLED_BY_DEFAULT=OFF \
            -DSDL_EVENTS_ENABLED_BY_DEFAULT=OFF \
            -DSDL_JOYSTICK_ENABLED_BY_DEFAULT=OFF \
            -DSDL_HAPTIC_ENABLED_BY_DEFAULT=OFF \
            -DSDL_POWER_ENABLED_BY_DEFAULT=OFF \
            -DSDL_THREADS_ENABLED_BY_DEFAULT=OFF \
            -DSDL_TIMERS_ENABLED_BY_DEFAULT=OFF \
            -DSDL_FILE_ENABLED_BY_DEFAULT=OFF \
            -DSDL_LOADSO_ENABLED_BY_DEFAULT=OFF \
            -DSDL_CPUINFO_ENABLED_BY_DEFAULT=OFF \
            -DSDL_FILESYSTEM_ENABLED_BY_DEFAULT=OFF \
            -DSDL_DLOPEN_ENABLED_BY_DEFAULT=OFF \
            -DSDL_SENSOR_ENABLED_BY_DEFAULT=OFF \
            -DSDL_LOCALE_ENABLED_BY_DEFAULT=OFF \
            ..

          cmake -LA ..
