name: Build deps

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  BUILD_CMD: -fno-stack-protector -O3 -msse3 -DNDEBUG main.c

jobs:
  build-linux:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          repository: libsdl-org/SDL

      - run: |
          mkdir build
          cd build
          cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang -DCMAKE_BUILD_TYPE=Release -D3DNOW=OFF -DBUILD_SHARED_LIBS=OFF -DSDL_SUBSYSTEMS=Video ..
          cmake -LA ..
