name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            dub_build: debug
            dub_compiler: dmd-latest
          - os: windows-latest
            dub_build: debug
            dub_compiler: dmd-latest

          - os: ubuntu-20.04
            dub_build: debug
            dub_compiler: ldc-latest
          - os: windows-latest
            dub_build: debug
            dub_compiler: ldc-latest

          - os: ubuntu-20.04
            dub_build: release-nobounds
            dub_compiler: dmd-latest
          - os: windows-latest
            dub_build: release-nobounds
            dub_compiler: dmd-latest

          - os: ubuntu-20.04
            dub_build: release-nobounds
            dub_compiler: ldc-latest
          - os: windows-latest
            dub_build: release-nobounds
            dub_compiler: ldc-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dub_compiler }}

      - if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: |
          sudo apt install -y libasound2-dev libxi-dev

      - working-directory: utils/opengl
        run: dub run

      - working-directory: utils/packets
        run: dub run

      - working-directory: utils/shaders
        run: dub run

      - run: |
          dub build -b ${{ matrix.dub_build }} -a x86_64
