name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            dub_arch: x86_64
            os: windows-latest
          - arch: x64
            dub_arch: x86_64
            os: ubuntu-20.04

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ldc-latest

      - working-directory: utils/packets
        run: |
          dub run
          
          
          
          
