name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            dub_build: debug
            dub_compiler: dmd-latest
          - os: windows-latest
            dub_build: debug
            dub_compiler: dmd-latest

          - os: ubuntu-20.04
            dub_build: debug
            dub_compiler: ldc-latest
          - os: windows-latest
            dub_build: debug
            dub_compiler: ldc-latest

          - os: ubuntu-20.04
            dub_build: release-nobounds
            dub_compiler: dmd-latest
          - os: windows-latest
            dub_build: release-nobounds
            dub_compiler: dmd-latest

          - os: ubuntu-20.04
            dub_build: release-nobounds
            dub_compiler: ldc-latest
          - os: windows-latest
            dub_build: release-nobounds
            dub_compiler: ldc-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dub_compiler }}

      - if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: |
          sudo apt install -y libasound2-dev libxi-dev
          sudo rm /usr/bin/ld
          sudo ln -s /usr/bin/ld.lld-11 /usr/bin/ld

      - working-directory: utils/opengl
        run: dub run

      - working-directory: utils/packets
        run: dub run

      - working-directory: utils/shaders
        run: dub run

      - run: dub build -b ${{ matrix.dub_build }} -a x86_64

      - working-directory: bin
        run: |
          7z a resources.zip data
          7z a ${{ matrix.os }}.7z aesir.json resources.zip perfontain*

      - uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.dub_compiler == 'ldc-latest' && matrix.dub_build == 'release-nobounds' }}
        with:
          files: |
            bin/${{ matrix.os }}.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
